### ISSUE TITLE
Add information

### ISSUE THREAD

**Issue by preeti-t** [preeti-t/pinkpanther#6]

**Comment by snicoll** [comment]
@preeti-t one issue == one task. You should rather have one issue for Rafael and one issue for Tahmina. 

Again, this sounds like a lot of work for just adding one file to the project but see this as an exercise to split the work amongst team members.

(also this exercise should have been done in the kingkong repo (today's project).

**Comment by preeti-t** [comment]
Okay I was about to ask you the same question.
